// Copyright 2026 Federico Runco (federico.runco@gmail.com)
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// 
// Licensed under the Solderpad Hardware License v2.1 (the “License”); 
// you may not use this file except in compliance with the License, or, 
// at your option, the Apache License version 2.0. You may obtain a copy 
// of the License at https://solderpad.org/licenses/SHL-2.1/
// 
// Unless required by applicable law or agreed to in writing, any work 
// distributed under the License is distributed on an “AS IS” BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
// License for the specific language governing permissions and limitations 
// under the License.

module baud_gen #(
	parameter int clk_freq = 50000000,
	// Autogenerated parameter, DO NOT CHANGE
	parameter int w = $clog2(clk_freq-1) 
) (
	input	logic			clk_i,
	input	logic 			rst_ni,
	input	logic[w-1:0] 	divider_i,
	output	logic			tick_o,
	output	logic			tick8_o
);

reg [w:0] cnt, cnt_os;

always_ff @ (posedge clk_i) begin
	if (!rst_ni) begin
		cnt <= '0;
		cnt_os <= '0;
	end else begin
		cnt <= cnt[w-1:0] + divider_i;
		cnt_os <= cnt_os[w-1:0] + (divider_i << 3);
	end
end

assign tick_o	= cnt[w];
assign tick8_o	= cnt_os[w];

endmodule